services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - ${FILE1}:/data/
    ports:
      - 90:80
    environment:
      - SIGNUPS_ALLOWED=false # make sure to disable this on your first build
     # - ADMIN_TOKEN=${TOKEN}
    restart: unless-stopped
