---
version: "3.9"
services:
  gluetun:
    image: qmcgaw/gluetun:v3.34.3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${FILE1}:/gluetun
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 6789:6789/udp #nzbget
      - 6789:6789/tcp #nzbget
      - 8080:8080 #qbit
      - 6881:6881 #qbit
      - 6881:6881/udp #qbit
    environment:
      - VPN_SERVICE_PROVIDER=${PROVIDER}
      - OPENVPN_USER=${USER}
      - OPENVPN_PASSWORD=${PASS}
      - SERVER_REGIONS=${REGION}
      - SERVER_HOSTNAMES=${SERVER_HOSTNAMES}
    restart: unless-stopped
    networks:
      - cloudflare

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - NZBGET_USER=${USER2} #optional
      - NZBGET_PASS=${PASS2} #optional
    volumes:
      - ${FILE2}:/config
      - ${FILE3}:/downloads #optional
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8080
    volumes:
      - ${FILE4}:/config
      - ${FILE3}:/downloads
    restart: unless-stopped
    
networks:
  cloudflare:
    external: true
